In [2]:
import gym

# Create environment

In [3]:
env = gym.make('CartPole-v0')

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


## Reset environment state

Need to do it **every time environment returns done**

In [4]:
env.reset()

array([ 0.0112476 ,  0.00527652,  0.03718234, -0.02749909])

## Render environment

In [ ]:
# This will stuck, see a proper implementation below
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample())

# Making steps


- **observation** (object): an environment-specific object representing your observation of the environment. For example, pixel data from a camera, joint angles and joint velocities of a robot, or the board state in a board game.
- **reward** (float): amount of reward achieved by the previous action. The scale varies between environments, but the goal is always to increase your total reward.
- **done** (boolean): whether it’s time to reset the environment again. Most (but not all) tasks are divided up into well-defined episodes, and done being True indicates the episode has terminated. (For example, perhaps the pole tipped too far, or you lost your last life.)
- **info** (dict): diagnostic information useful for debugging. It can sometimes be useful for learning (for example, it might contain the raw probabilities behind the environment’s last state change). However, official evaluations of your agent are not allowed to use this for learning.


## Run test environment

In [5]:
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

[-0.04101566  0.00595479  0.03571546 -0.03072233]
[-0.04089657 -0.18966065  0.03510101  0.27301183]
[-0.04468978  0.00494333  0.04056125 -0.00839676]
[-0.04459091  0.19946081  0.04039331 -0.28801126]
[-0.0406017   0.0037868   0.03463309  0.01713274]
[-0.04052596  0.1983954   0.03497574 -0.26442502]
[-0.03655805  0.39300113  0.02968724 -0.54587431]
[-0.02869803  0.58769365  0.01876976 -0.82905764]
[-0.01694416  0.78255404  0.0021886  -1.11577876]
[-1.29307814e-03  9.77647195e-01 -2.01269726e-02 -1.40777434e+00]
[ 0.01825987  1.17301302 -0.04828246 -1.70668065]
[ 0.04172013  1.36865583 -0.08241607 -2.01399241]
[ 0.06909324  1.17448102 -0.12269592 -1.74792172]
[ 0.09258286  0.98094841 -0.15765435 -1.49578735]
[ 0.11220183  1.17759669 -0.1875701  -1.83326022]
Episode finished after 15 timesteps
[ 0.01633868  0.00863254 -0.01568695  0.0067011 ]
[ 0.01651133 -0.18626096 -0.01555293  0.29439362]
[ 0.01278611 -0.38115777 -0.00966506  0.58213109]
[ 0.00516295 -0.57614298  0.00197757  0.87175376

[ 0.02817826  0.01630612 -0.05759256 -0.07069979]
[ 0.02850439  0.21220444 -0.05900656 -0.38098292]
[ 0.03274848  0.01796784 -0.06662622 -0.10747295]
[ 0.03310783  0.21397816 -0.06877567 -0.42040972]
[ 0.0373874   0.01989467 -0.07718387 -0.15017684]
[ 0.03778529  0.21603213 -0.08018741 -0.46617666]
[ 0.04210593  0.02212931 -0.08951094 -0.19980687]
[ 0.04254852  0.21840989 -0.09350708 -0.51933013]
[ 0.04691672  0.02472015 -0.10389368 -0.25751579]
[ 0.04741112 -0.16877695 -0.10904399  0.000675  ]
[ 0.04403558 -0.36217981 -0.10903049  0.25706081]
[ 0.03679198 -0.16568382 -0.10388928 -0.06792449]
[ 0.03347831 -0.35917476 -0.10524777  0.19025852]
[ 0.02629481 -0.16271688 -0.1014426  -0.13368341]
[ 0.02304047 -0.35625049 -0.10411627  0.12535161]
[ 0.01591546 -0.15980298 -0.10160923 -0.19827887]
[ 0.01271941 -0.3533359  -0.10557481  0.06070148]
[ 0.00565269 -0.54679817 -0.10436078  0.31829776]
[-0.00528328 -0.74029093 -0.09799483  0.57633142]
[-0.02008909 -0.93391257 -0.0864682   0.83660608]


[ 0.00315567  1.21044022 -0.07539379 -1.80401302]
[ 0.02736447  1.0162369  -0.11147406 -1.53568035]
[ 0.04768921  0.82261981 -0.14218766 -1.27976287]
[ 0.06414161  0.6295669  -0.16778292 -1.0347683 ]
[ 0.07673294  0.43702474 -0.18847829 -0.7991078 ]
[ 0.08547344  0.63416307 -0.20446044 -1.14466358]
Episode finished after 20 timesteps
[-0.03150662 -0.03325766 -0.04927018 -0.02986916]
[-0.03217177 -0.22763969 -0.04986756  0.24687048]
[-0.03672456 -0.03184231 -0.04493015 -0.06111547]
[-0.03736141 -0.22629223 -0.04615246  0.21706002]
[-0.04188725 -0.42072506 -0.04181126  0.49483471]
[-0.05030176 -0.22503918 -0.03191457  0.18927349]
[-0.05480254 -0.41969035 -0.0281291   0.47172027]
[-0.06319635 -0.22418262 -0.01869469  0.17030583]
[-0.06768    -0.41903207 -0.01528858  0.45703301]
[-0.07606064 -0.22369735 -0.00614792  0.15957051]
[-0.08053459 -0.41873075 -0.00295651  0.4503076 ]
[-0.0889092  -0.61381076  0.00604965  0.74205712]
[-0.10118542 -0.8090157   0.02089079  1.03663776]
[-0.11736573 -

# Spaces

Every environment comes with an action_space and an observation_space. These attributes are of type Space, and they describe the format of valid actions and observations.

The Discrete space allows a fixed range of non-negative numbers, so in cart pole case valid actions are either 0 or 1. The Box space represents an n-dimensional box, so valid observations will be an array of 4 numbers. We can also check the Box’s bounds.

In [6]:
print(env.action_space)
print(env.observation_space)

# checking box bounds
print(env.observation_space.high)
print(env.observation_space.low)

Discrete(2)
Box(4,)
[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


In [7]:
# Check if something belogns to space

from gym import spaces
space = spaces.Discrete(8) # Set with 8 elements {0, 1, 2, ..., 7}
x = space.sample()
assert space.contains(x)
assert space.n == 8

# Environments

In [9]:
# List available environments

from gym import envs
print(envs.registry.all())

dict_values([EnvSpec(Copy-v0), EnvSpec(RepeatCopy-v0), EnvSpec(ReversedAddition-v0), EnvSpec(ReversedAddition3-v0), EnvSpec(DuplicatedInput-v0), EnvSpec(Reverse-v0), EnvSpec(CartPole-v0), EnvSpec(CartPole-v1), EnvSpec(MountainCar-v0), EnvSpec(MountainCarContinuous-v0), EnvSpec(Pendulum-v0), EnvSpec(Acrobot-v1), EnvSpec(LunarLander-v2), EnvSpec(LunarLanderContinuous-v2), EnvSpec(BipedalWalker-v2), EnvSpec(BipedalWalkerHardcore-v2), EnvSpec(CarRacing-v0), EnvSpec(Blackjack-v0), EnvSpec(KellyCoinflip-v0), EnvSpec(KellyCoinflipGeneralized-v0), EnvSpec(FrozenLake-v0), EnvSpec(FrozenLake8x8-v0), EnvSpec(CliffWalking-v0), EnvSpec(NChain-v0), EnvSpec(Roulette-v0), EnvSpec(Taxi-v2), EnvSpec(GuessingGame-v0), EnvSpec(HotterColder-v0), EnvSpec(Reacher-v2), EnvSpec(Pusher-v2), EnvSpec(Thrower-v2), EnvSpec(Striker-v2), EnvSpec(InvertedPendulum-v2), EnvSpec(InvertedDoublePendulum-v2), EnvSpec(HalfCheetah-v2), EnvSpec(Hopper-v2), EnvSpec(Swimmer-v2), EnvSpec(Walker2d-v2), EnvSpec(Ant-v2), EnvSpec(Hum